import Head from 'next/head'
import { useState, useEffect } from 'react'
import { loadData } from '../components/services'
import Formulario from '../components/Formulario'
import axios from 'axios'
export default function Home() {
  const [lista, setLista] = useState([])
  const [open, setOpen] = useState(false)
  const [item, setItem] = useState(null)
  const onCancel = () => {
    setOpen(false)
    setItem(null)

  }
  const showModal = () => {
    setOpen(true)
    setItem(null)

  }
  const onOk = async (formulario) => {
    if(item == null){
      nuevaTarea(formulario)
    }
    else{
      saveEdit(formulario)
    }

  }
  const nuevaTarea = async (formulario)=>{
    formulario.status = false
    const nuevaTarea = await axios.post('http://localhost:8080/Tasks', formulario)
    const auxData = lista
    auxData.unshift(
      { ...nuevaTarea.data }
    )
    setLista(auxData)
    setOpen(false)
  }
  const saveEdit= async (formulario)=>{
    formulario.status = false
    const editarTarea = await axios.put(`http://localhost:8080/Tasks/${item.id}`, formulario)
    const index = lista.findIndex((item) => item.id == editarTarea.data.id )
    const auxData = lista
    auxData[index] ={
      ...editarTarea.data
    }
    setLista(auxData)
    setOpen(false)
  }
  const cargarDatos = async () => {
    const listaDeTareas = await axios.get('http://localhost:8080/Tasks')
    setLista(listaDeTareas.data)
  }
  const Eliminar = async (valor) => {
    const seleccionado = lista[valor].id
    const auxData = lista.filter((item) => item.id !== seleccionado)
    setLista(auxData)
    await axios.delete(`http://localhost:8080/Tasks/${seleccionado}`)

  }
  const Editar = async (valor) => {
    setOpen(true)
    setItem(lista[valor])
    console.log(lista[valor])

  }

  useEffect(() => { cargarDatos() }, [])

  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <h1>Inicio</h1>
        <div className='flex'>
          <button onClick={showModal} className='ml-5 p-3 text-white hover:bg-black bg-blue-500'>Agregar</button>

          <Formulario open={open} onCancel={onCancel} array={onOk} tarea={item} />
        </div>
        <div className='m-auto w-3/6 bg-blue-500 grid gap-4 mb-12 py-2'>
          <h1 className='text-center text-2xl text-white'>Lista de tareas</h1>
          {lista.map(function (item, index) {
            return (
              <div key={item.id} className='bg-slate-500 mx-2'>
                <h1 className='text-xl flex justify-between' ><span className='ml-3' >{item.name} </span>  <span className='mr-3'>Nm.{item.id}</span> </h1>
                <div className=' bg-white p-3'>
                  {item.description}
                </div>
                <div className='text-end' >
                  <button onClick={() => Editar(index)} className=' mr-5 my-2 px-3 py-1 text-white hover:bg-white hover:text-black bg-blue-500'>Editar</button>
                  <button onClick={() => Eliminar(index)} className='mr-5 my-2 px-3 py-1 text-white hover:bg-white hover:text-black bg-blue-500'>Eliminar</button>
                </div>
              </div>


            )
          })}

        </div>
      </main>

      <footer >

      </footer>
    </div>
  )
}
